### ISSUE TITLE
关于DictConfig不可调用的问题

### ISSUE THREAD

**Issue by HelloRuccs** [LetterLiGo/SafeEar#10]
开发者你好 我在训练的过程中遇到了`DictConfig' object is not callable`的问题

定位到的DictConfig是这句`def train(cfg: DictConfig) -> Tuple[Dict[str, Any], Dict[str, Any]]:`
事故发生的情景是本来昨晚训练是可以的 但是突然断网了造成训练中止，然后今天早上再训的时候就发生了如下错误
``` 
 File "train.py", line 105, in <module>
    train(cfg)
  File "train.py", line 49, in train
    callbacks: List[Callback] = []
  File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 951, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/nfs/chenjiawei123/SafeEar-main/safeear/datas/asvspoof19.py", line 234, in setup
    self.data_train = self.hparams.DataClass("train")
TypeError: 'DictConfig' object is not callable
wandb: Waiting for W&B process to finish... (failed 1).
wandb: You can sync this run to the cloud by running:ped)
wandb: wandb sync Exps//ASVspoof19/logs/wandb/offline-run-20241020_112914-y2wscbfh
wandb: Find logs at: Exps//ASVspoof19/logs/wandb/offline-run-20241020_112914-y2wscbfh/logs
```

**Comment by JusperLee** [comment]
请您给一个报错截图

**Comment by HelloRuccs** [comment]
![image](https://github.com/user-attachments/assets/1ad73f71-ef84-43a8-b1cd-983386c1bfda)

**Comment by HelloRuccs** [comment]
> ![image](https://private-user-images.githubusercontent.com/100855761/378832402-1ad73f71-ef84-43a8-b1cd-983386c1bfda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTk1NzEsIm5iZiI6MTcyOTU5OTI3MSwicGF0aCI6Ii8xMDA4NTU3NjEvMzc4ODMyNDAyLTFhZDczZjcxLWVmODQtNDNhOC1iMWNkLTk4MzM4NmMxYmZkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxMjE0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzViNWU5ZDk0MmY3NjI1MWY2ZTQ5NmUzYzBiYTc2ODRmMDY0MDk1NWQ0MzE0MmU5NTRkZGQ2NmRmZDk1NzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nsHZpXVlislH87UX86ZiTSeoLVrNd6on2YCcbkWvUa8)

开发者你好，这是我的报错截图，很抱歉这会因此占用你的一点时间

**Comment by JusperLee** [comment]
我认为是你的版本问题。
omegaconf                2.1.2

**Comment by HelloRuccs** [comment]
> 我认为是你的版本问题。 omegaconf 2.1.2

开发者你好 我讲omegaconf改为2.1.2后发现会与fairseq==0.12.2冲突 然后观察开发者的fairseq==1.0.0a0+4acaa61好像是pip install -e fairseq_ours 但是我装出来的版本是fairseq 0.12.2 所以想请问一下如何安装fairseq==1.0.0a0+4acaa61

**Comment by LetterLiGo** [comment]
Thanks for your question:) Find this page: https://github.com/LetterLiGo/SafeEar/tree/main/fairseq_ours

you would see we have uploaded the customized fairseq lib, then you 
```
cd fairseq
pip install --editable ./
```

**Comment by HelloRuccs** [comment]
![image](https://github.com/user-attachments/assets/6ed5ca69-407b-4ace-a5d4-4660f44e67a7)
我尝试了一下 报了如上图错误 它显示说does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
 只在fairseq_ours看到了setup.py

**Comment by HelloRuccs** [comment]
![image](https://github.com/user-attachments/assets/ffb411f6-3827-441a-9b3d-c99180d74016)
报了如下错 setup.py貌似只在fairseq_ours存在
![image](https://github.com/user-attachments/assets/c523c7b7-0e85-4d03-871f-190439c6e21e)

**Comment by LetterLiGo** [comment]
在fairseq_ours这个目录下的setup.py进行安装

**Comment by HelloRuccs** [comment]
> 在fairseq_ours这个目录下的setup.py进行安装

开发者你好 后续我处理好fairseq也保持和你的版本一致但是报了这个错
![image](https://github.com/user-attachments/assets/b6089178-df0a-4a85-b08e-9c07e9b97690) 
这个错我在[#issue8](https://github.com/LetterLiGo/SafeEar/issues/8#issue-2597934976)
提及过，在那个问题下也有别的同学提到 所以想请问一下如何解决 谢谢

**Comment by littleJu1y** [comment]
> 开发者你好 我在训练的过程中遇到了`DictConfig' object is not callable`的问题
> 
> 定位到的DictConfig是这句`def train(cfg: DictConfig) -> Tuple[Dict[str, Any], Dict[str, Any]]:` 事故发生的情景是本来昨晚训练是可以的 但是突然断网了造成训练中止，然后今天早上再训的时候就发生了如下错误
> 
> ```
>  File "train.py", line 105, in <module>
>     train(cfg)
>   File "train.py", line 49, in train
>     callbacks: List[Callback] = []
>   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
>     call._call_and_handle_interrupt(
>   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
>     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
>   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
>     return function(*args, **kwargs)
>   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
>     self._run(model, ckpt_path=ckpt_path)
>   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 951, in _run
>     call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
>   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 92, in _call_setup_hook
>     _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
>   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
>     return fn(*args, **kwargs)
>   File "/nfs/chenjiawei123/SafeEar-main/safeear/datas/asvspoof19.py", line 234, in setup
>     self.data_train = self.hparams.DataClass("train")
> TypeError: 'DictConfig' object is not callable
> wandb: Waiting for W&B process to finish... (failed 1).
> wandb: You can sync this run to the cloud by running:ped)
> wandb: wandb sync Exps//ASVspoof19/logs/wandb/offline-run-20241020_112914-y2wscbfh
> wandb: Find logs at: Exps//ASVspoof19/logs/wandb/offline-run-20241020_112914-y2wscbfh/logs
> ```



请问我可以加您的联系方式嘛，我也遇到了一样的问题

**Comment by JusperLee** [comment]
omegaconf 2.1.2

**Comment by JusperLee** [comment]
> > 在fairseq_ours这个目录下的setup.py进行安装
> 
> 开发者你好 后续我处理好fairseq也保持和你的版本一致但是报了这个错 ![image](https://private-user-images.githubusercontent.com/100855761/383065085-b6089178-df0a-4a85-b08e-9c07e9b97690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTQ0NDMsIm5iZiI6MTczMTMxNDE0MywicGF0aCI6Ii8xMDA4NTU3NjEvMzgzMDY1MDg1LWI2MDg5MTc4LWRmMGEtNGE4NS1iMDhlLTljMDdlOWI5NzY5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwODM1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjFlMGNkMDEzZmM5MmIyMGMwMDc5NTc1NDZjOWJlNmIxMWRjNDBlMmM5NzdhNmQ5NGMzNTkyMTRlZTcxMWUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5IQk4WP5r3hL-Z1_8UEC7M_SY8-usvKULmJCLpPureo) 这个错我在[#issue8](https://github.com/LetterLiGo/SafeEar/issues/8#issue-2597934976) 提及过，在那个问题下也有别的同学提到 所以想请问一下如何解决 谢谢

你的数据长度是多少？这个可能是你的数据长度的原因，你使用的数据集是那个？

**Comment by HelloRuccs** [comment]
> > > 在fairseq_ours这个目录下的setup.py进行安装
> > 
> > 
> > 开发者你好 后续我处理好fairseq也保持和你的版本一致但是报了这个错 ![image](https://private-user-images.githubusercontent.com/100855761/383065085-b6089178-df0a-4a85-b08e-9c07e9b97690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTQ0NDMsIm5iZiI6MTczMTMxNDE0MywicGF0aCI6Ii8xMDA4NTU3NjEvMzgzMDY1MDg1LWI2MDg5MTc4LWRmMGEtNGE4NS1iMDhlLTljMDdlOWI5NzY5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwODM1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjFlMGNkMDEzZmM5MmIyMGMwMDc5NTc1NDZjOWJlNmIxMWRjNDBlMmM5NzdhNmQ5NGMzNTkyMTRlZTcxMWUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5IQk4WP5r3hL-Z1_8UEC7M_SY8-usvKULmJCLpPureo) 这个错我在[#issue8](https://github.com/LetterLiGo/SafeEar/issues/8#issue-2597934976) 提及过，在那个问题下也有别的同学提到 所以想请问一下如何解决 谢谢
> 
> 你的数据长度是多少？这个可能是你的数据长度的原因，你使用的数据集是那个？

2019ASvsproof

**Comment by HelloRuccs** [comment]
> > 开发者你好 我在训练的过程中遇到了`DictConfig' object is not callable`的问题
> > 定位到的DictConfig是这句`def train(cfg: DictConfig) -> Tuple[Dict[str, Any], Dict[str, Any]]:` 事故发生的情景是本来昨晚训练是可以的 但是突然断网了造成训练中止，然后今天早上再训的时候就发生了如下错误
> > ```
> >  File "train.py", line 105, in <module>
> >     train(cfg)
> >   File "train.py", line 49, in train
> >     callbacks: List[Callback] = []
> >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
> >     call._call_and_handle_interrupt(
> >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
> >     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
> >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
> >     return function(*args, **kwargs)
> >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
> >     self._run(model, ckpt_path=ckpt_path)
> >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 951, in _run
> >     call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
> >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 92, in _call_setup_hook
> >     _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
> >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
> >     return fn(*args, **kwargs)
> >   File "/nfs/chenjiawei123/SafeEar-main/safeear/datas/asvspoof19.py", line 234, in setup
> >     self.data_train = self.hparams.DataClass("train")
> > TypeError: 'DictConfig' object is not callable
> > wandb: Waiting for W&B process to finish... (failed 1).
> > wandb: You can sync this run to the cloud by running:ped)
> > wandb: wandb sync Exps//ASVspoof19/logs/wandb/offline-run-20241020_112914-y2wscbfh
> > wandb: Find logs at: Exps//ASVspoof19/logs/wandb/offline-run-20241020_112914-y2wscbfh/logs
> > ```
> 
> 请问我可以加您的联系方式嘛，我也遇到了一样的问题

可以的 你可以邮箱私聊加我

**Comment by littleJu1y** [comment]
> > > 开发者你好 我在训练的过程中遇到了`DictConfig' object is not callable`的问题
> > > 定位到的DictConfig是这句`def train(cfg: DictConfig) -> Tuple[Dict[str, Any], Dict[str, Any]]:` 事故发生的情景是本来昨晚训练是可以的 但是突然断网了造成训练中止，然后今天早上再训的时候就发生了如下错误
> > > ```
> > >  File "train.py", line 105, in <module>
> > >     train(cfg)
> > >   File "train.py", line 49, in train
> > >     callbacks: List[Callback] = []
> > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
> > >     call._call_and_handle_interrupt(
> > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
> > >     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
> > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
> > >     return function(*args, **kwargs)
> > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
> > >     self._run(model, ckpt_path=ckpt_path)
> > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 951, in _run
> > >     call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
> > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 92, in _call_setup_hook
> > >     _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
> > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
> > >     return fn(*args, **kwargs)
> > >   File "/nfs/chenjiawei123/SafeEar-main/safeear/datas/asvspoof19.py", line 234, in setup
> > >     self.data_train = self.hparams.DataClass("train")
> > > TypeError: 'DictConfig' object is not callable
> > > wandb: Waiting for W&B process to finish... (failed 1).
> > > wandb: You can sync this run to the cloud by running:ped)
> > > wandb: wandb sync Exps//ASVspoof19/logs/wandb/offline-run-20241020_112914-y2wscbfh
> > > wandb: Find logs at: Exps//ASVspoof19/logs/wandb/offline-run-20241020_112914-y2wscbfh/logs
> > > ```
> > 
> > 
> > 请问我可以加您的联系方式嘛，我也遇到了一样的问题
> 
> 可以的 你可以邮箱私聊加我

请问您的邮箱是多少？我好像没找到您的邮箱。。。

**Comment by HelloRuccs** [comment]
> > > > 开发者你好 我在训练的过程中遇到了`DictConfig' object is not callable`的问题
> > > > 定位到的DictConfig是这句`def train(cfg: DictConfig) -> Tuple[Dict[str, Any], Dict[str, Any]]:` 事故发生的情景是本来昨晚训练是可以的 但是突然断网了造成训练中止，然后今天早上再训的时候就发生了如下错误
> > > > ```
> > > >  File "train.py", line 105, in <module>
> > > >     train(cfg)
> > > >   File "train.py", line 49, in train
> > > >     callbacks: List[Callback] = []
> > > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
> > > >     call._call_and_handle_interrupt(
> > > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
> > > >     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
> > > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
> > > >     return function(*args, **kwargs)
> > > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
> > > >     self._run(model, ckpt_path=ckpt_path)
> > > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 951, in _run
> > > >     call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
> > > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 92, in _call_setup_hook
> > > >     _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
> > > >   File "/home/chenjiawei123/yes/envs/Lxf-safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
> > > >     return fn(*args, **kwargs)
> > > >   File "/nfs/chenjiawei123/SafeEar-main/safeear/datas/asvspoof19.py", line 234, in setup
> > > >     self.data_train = self.hparams.DataClass("train")
> > > > TypeError: 'DictConfig' object is not callable
> > > > wandb: Waiting for W&B process to finish... (failed 1).
> > > > wandb: You can sync this run to the cloud by running:ped)
> > > > wandb: wandb sync Exps//ASVspoof19/logs/wandb/offline-run-20241020_112914-y2wscbfh
> > > > wandb: Find logs at: Exps//ASVspoof19/logs/wandb/offline-run-20241020_112914-y2wscbfh/logs
> > > > ```
> > > 
> > > 
> > > 请问我可以加您的联系方式嘛，我也遇到了一样的问题
> > 
> > 
> > 可以的 你可以邮箱私聊加我
> 
> 请问您的邮箱是多少？我好像没找到您的邮箱。。。

3555621195 这是我的q号

**Comment by guanghuili98** [comment]
> > 在fairseq_ours这个目录下的setup.py进行安装
> 
> 开发者你好 后续我处理好fairseq也保持和你的版本一致但是报了这个错 ![image](https://private-user-images.githubusercontent.com/100855761/383065085-b6089178-df0a-4a85-b08e-9c07e9b97690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjgyMTMsIm5iZiI6MTczMjE2NzkxMywicGF0aCI6Ii8xMDA4NTU3NjEvMzgzMDY1MDg1LWI2MDg5MTc4LWRmMGEtNGE4NS1iMDhlLTljMDdlOWI5NzY5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwNTQ1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzJhZmJmZmI5NTIzNDJmODI5NWEyNjJiM2I4YmE4ZTEwMzc4NDAzODZhNjJjYTUwYzYzMjA2OTg1YTRiMDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ThcHFcyERdvq1Ugjo-gUeL8wz5pqOG-OFaqmWyq-T9Q) 这个错我在[#issue8](https://github.com/LetterLiGo/SafeEar/issues/8#issue-2597934976) 提及过，在那个问题下也有别的同学提到 所以想请问一下如何解决 谢谢

请问这个问题你解决了吗?

**Comment by HelloRuccs** [comment]
> 请问这个问题你解决了吗?
我已经解决了 你需要修改safeear_trainer.py以及ASvsproof19.py
