### ISSUE TITLE
数据集CVoiceFake标注

### ISSUE THREAD

**Issue by JingyangXu1991** [LetterLiGo/SafeEar#12]
你好，想请问下数据集CVoiceFake是否有公开标注文件，目前只看到数据没有找到标注文件呢

**Comment by LetterLiGo** [comment]
Hi, thank you for your attention. CVoiceFake can be used for deepfake detection, just like ASVSpoof 2019 and 2021, as indicated by its folder name. Inside, you will find a section called "Bonafide," which includes genuine audio samples from CommonVoice in five different languages.
**1. Bonafide**

1. diffwave_generated
2. griffin_lim_generated
3. vctk_multi_band_melgan.v2_generated
4. vctk_parallel_wavegan.v1_generated
5. vctk_style_melgan.v1_generated
6. world_generated

Additionally, there are folders dedicated to cloning and synthesizing audio using six representative techniques. Please note that we have recently released our DiffWave subset on Zenodo. You can download the file named CVoiceFake_Large_diffwave_update.tar.gz.xx, and after unzipping it, you will find it retains the same file structure as before.
  **| CVoiceFake_Large_diffwave_update.tar.gz.00 |
  | CVoiceFake_Large_diffwave_update.tar.gz.01   |**
