### ISSUE TITLE
测试结果与论文中的误差问题

### ISSUE THREAD

**Issue by HelloRuccs** [LetterLiGo/SafeEar#15]
开发者你好，我之前问题问的比较多很抱歉。测试代码已经跑通，但是我跑出的效果最好就
![K0N$3FSS)%R9(O0RL(`%}CT](https://github.com/user-attachments/assets/8ac9cdd0-53ca-47a7-b744-af9880874507)
与论文中的3.10%差距有点大

**Comment by LetterLiGo** [comment]
Thank you, but a 37.879% EER seems incorrect. I will show you a screenshot of our intermediate results from development. Please note that they are not optimal.

<img width="1026" alt="image" src="https://github.com/user-attachments/assets/54509a49-7624-4a39-b46b-a248d38d39a6">

**Comment by HelloRuccs** [comment]
> Maybe you train the model with very few epochs?

对的 训练epoch是5轮

**Comment by LetterLiGo** [comment]
Ok, try classifier retraining with at least 20-40 epochs. Test well-trained classifier on val and eval datasets. Feel free to reach me if you have further questions.

**Comment by HelloRuccs** [comment]
> Ok, try classifier retraining with at least 20-40 epochs. Test well-trained classifier on the val and the eval datasets. Feel free to reach out if you have further questions.

开发者你好 我val_eer最好的效果是0.369 但是测试的结果大概是0.0611。想问一下你们团队当时训出来最好的val_eer大概是多少 谢谢

**Comment by jun-mei** [comment]
兄弟，想问一下最后怎么解决问题不匹配问题的

**Comment by HelloRuccs** [comment]
> 兄弟，想问一下最后怎么解决问题不匹配问题的

需要修改ASvspoof19.py和safeear_trainer.py 具体你可以加我q3555621195

**Comment by guanghuili98** [comment]
> 开发者你好，我之前问题问的比较多很抱歉。测试代码已经跑通，但是我跑出的效果最好就 ![K0N$3FSS)%R9(O0RL(`%}CT](https://private-user-images.githubusercontent.com/100855761/386527028-8ac9cdd0-53ca-47a7-b744-af9880874507.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNTQxOTEsIm5iZiI6MTczMjI1Mzg5MSwicGF0aCI6Ii8xMDA4NTU3NjEvMzg2NTI3MDI4LThhYzljZGQwLTUzY2EtNDdhNy1iNzQ0LWFmOTg4MDg3NDUwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwNTM4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGE0MzFkNWNhNWJkYTc4YTNjZjQ0NjMyNDI4NmQ1MDQxMTNiOWMyZDYyZDNmOWMwYjE5M2E5MTFmYjg0MjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CuQmOLjOlYxgbvI5f1n_SOmYwGbCvjCw4KtI7cBn0IE) 与论文中的3.10%差距有点大

你好，请问你是如何将eval_eer从37%提升到6%的呢？

**Comment by HelloRuccs** [comment]
> > 开发者你好，我之前问题问的比较多很抱歉。测试代码已经跑通，但是我跑出的效果最好就 ![K0N$3FSS)%R9(O0RL(`%}CT](https://private-user-images.githubusercontent.com/100855761/386527028-8ac9cdd0-53ca-47a7-b744-af9880874507.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNTQxOTEsIm5iZiI6MTczMjI1Mzg5MSwicGF0aCI6Ii8xMDA4NTU3NjEvMzg2NTI3MDI4LThhYzljZGQwLTUzY2EtNDdhNy1iNzQ0LWFmOTg4MDg3NDUwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwNTM4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGE0MzFkNWNhNWJkYTc4YTNjZjQ0NjMyNDI4NmQ1MDQxMTNiOWMyZDYyZDNmOWMwYjE5M2E5MTFmYjg0MjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CuQmOLjOlYxgbvI5f1n_SOmYwGbCvjCw4KtI7cBn0IE) 与论文中的3.10%差距有点大
> 
> 你好，请问你是如何将eval_eer从37%提升到6%的呢？

增加训练轮数，20-40轮差不多，然后训出最好的权重后，通过--ckpt_path指定最好的权重文件

**Comment by lemnsoda** [comment]
> > Ok, try classifier retraining with at least 20-40 epochs. Test well-trained classifier on the val and the eval datasets. Feel free to reach out if you have further questions.
> 
> 开发者你好 我val_eer最好的效果是0.369 但是测试的结果大概是0.0611。想问一下你们团队当时训出来最好的val_eer大概是多少 谢谢

你好，我想请问一下后续关于这个模型你还有提升吗，大概能到什么程度，我测试的时候也感觉差距有些大

**Comment by thrgram-sketch** [comment]
> > > Ok, try classifier retraining with at least 20-40 epochs. Test well-trained classifier on the val and the eval datasets. Feel free to reach out if you have further questions.
> > 
> > 
> > 开发者你好 我val_eer最好的效果是0.369 但是测试的结果大概是0.0611。想问一下你们团队当时训出来最好的val_eer大概是多少 谢谢
> 
> 你好，我想请问一下后续关于这个模型你还有提升吗，大概能到什么程度，我测试的时候也感觉差距有些大

我也想请问一下，之后是要怎么提升，我也是测试到了0.06之后就没有提升了
