### ISSUE TITLE
下载依赖requirement.tet，遇到问题

### ISSUE THREAD

**Issue by Zhzdpaaa** [LetterLiGo/SafeEar#3]
$ pip install -r requirements.txt
ERROR: /data5/likai/SpoofD/fairseq-a54021305d6b3c4c5959ac9395135f63202db8f1 is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
看报错，应该是 requirements.txt 里，这两行有问题
\# Editable install with no version control (fairseq==1.0.0a0)
-e /data5/likai/SpoofD/fairseq-a54021305d6b3c4c5959ac9395135f63202db8f1
想问问佬们，这个路径是哪里的呀

**Comment by LetterLiGo** [comment]
Please kindly check our updated code

1. We uploaded the modified fairseq library, which is used for dumping HuBERT features.
2. Fixed the requirement.txt
