### ISSUE TITLE
貌似没有看到paper中提到的环境增强代码

### ISSUE THREAD

**Issue by JJun-Guo** [LetterLiGo/SafeEar#5]
真实环境增强（Real-world Augment）
鉴于现实世界的信道多样性，采用具有代表性的音频编解码器（如G.711、G.722、gsm、vorbis、ogg）进行数据增强，模拟实际环境中带宽、码率的多样性，以推广到不可见通信场景。

**Comment by JusperLee** [comment]
这个你可以查看Dataset

https://github.com/LetterLiGo/SafeEar/blob/298691e15172670d8f708bb1fc59d972bcc7eaf7/safeear/datas/asvspoof21.py#L100
